name: flutter_confetti_plus
description: A Flutter confetti package with quick overlays, controller-based widgets, emoji particles, widget sprites, and Konfetti-style party presets.

version: 0.0.2

homepage: https://github.com/shirsh94/flutter_confetti_plus
repository: https://github.com/shirsh94/flutter_confetti_plus
issue_tracker: https://github.com/shirsh94/flutter_confetti_plus/issues

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  vector_math: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
